# Etap 1: Budowanie (Build) - używamy Node.js, aby skompilować Reacta
FROM node:20-alpine AS build

WORKDIR /app

# Kopiujemy pliki package.json oraz package-lock.json (lub yarn.lock)
COPY package*.json ./

# Instalujemy zależności
RUN npm install

# Kopiujemy resztę plików
COPY . .

# Budujemy aplikację
RUN npm run build  # Zmieniaj na 'vite build', jeśli używasz Vite

# Etap 2: Serwowanie (Production) - używamy lekkiego serwera Nginx
FROM nginx:alpine

# Kopiujemy wynikowy build do folderu Nginx
COPY --from=build /app/dist /usr/share/nginx/html  # Zmieniaj 'dist' na 'build', jeśli używasz Create React App

# Ekspozycja portu 80 dla aplikacji
EXPOSE 80

# Uruchamiamy Nginx
CMD ["nginx", "-g", "daemon off;"]
 